version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: always

  frontend:
    image: node:18-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    restart: always
